@startuml
'https://plantuml.com/sequence-diagram

autonumber

企业微信主页面 -> 通讯录页面:点击通讯录

通讯录页面 -> 添加成员页面: 点击添加成员

通讯录页面 -> 添加部门页面: 点击+ 添加部门
通讯录页面 -> 导入通讯录页面: 点击批量导入/到处\n文件导入
添加成员页面 -> 通讯录页面:添加成员完成
通讯录页面 -> 通讯录页面:检查添加成员列表
添加部门页面 -> 通讯录页面: 添加部门完成
通讯录页面 -> 通讯录页面:检查添加部门列表
添加部门页面 -> 添加成员页面:点击添加成员
添加部门页面 -> 导入通讯录页面:点击批量导入 文件导入
导入通讯录页面 -> 通讯录页面: 导入通讯录完成
通讯录页面 -> 通讯录页面:检查导入通讯录列表
导入通讯录页面 -> 导入通讯录页面:点击上传文件继续导入
添加成员页面 -> 添加部门页面:点击+ 添加部门


@enduml